# Generated by Django 4.1.11 on 2023-10-31 23:32

import athanor.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("typeclasses", "0016_alter_attribute_id_alter_tag_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardCollectionDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "db_typeclass_path",
                    models.CharField(
                        db_index=True,
                        help_text="this defines what 'type' of entity this is. This variable holds a Python path to a module with a valid Evennia Typeclass.",
                        max_length=255,
                        null=True,
                        verbose_name="typeclass",
                    ),
                ),
                (
                    "db_date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "db_lock_storage",
                    models.TextField(
                        blank=True,
                        help_text="locks limit access to an entity. A lock is defined as a 'lock string' on the form 'type:lockfunctions', defining what functionality is locked and how to determine access. Not defining a lock means no access is granted.",
                        verbose_name="locks",
                    ),
                ),
                ("db_key", models.CharField(blank=True, max_length=255, unique=True)),
                (
                    "db_abbreviation",
                    models.CharField(blank=True, max_length=30, unique=True),
                ),
                ("db_config", models.JSONField(default=dict)),
                (
                    "db_attributes",
                    models.ManyToManyField(
                        help_text="attributes on this object. An attribute can hold any pickle-able python object (see docs for special cases).",
                        to="typeclasses.attribute",
                    ),
                ),
                (
                    "db_tags",
                    models.ManyToManyField(
                        help_text="tags on this object. Tags are simple string markers to identify, group and alias objects.",
                        to="typeclasses.tag",
                    ),
                ),
                ("db_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Evennia Database Object",
                "ordering": ["-db_date_created", "id", "db_typeclass_path", "db_key"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BoardDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "db_key",
                    models.CharField(db_index=True, max_length=255, verbose_name="key"),
                ),
                (
                    "db_typeclass_path",
                    models.CharField(
                        db_index=True,
                        help_text="this defines what 'type' of entity this is. This variable holds a Python path to a module with a valid Evennia Typeclass.",
                        max_length=255,
                        null=True,
                        verbose_name="typeclass",
                    ),
                ),
                (
                    "db_date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "db_lock_storage",
                    models.TextField(
                        blank=True,
                        help_text="locks limit access to an entity. A lock is defined as a 'lock string' on the form 'type:lockfunctions', defining what functionality is locked and how to determine access. Not defining a lock means no access is granted.",
                        verbose_name="locks",
                    ),
                ),
                ("db_order", models.IntegerField(default=1)),
                ("db_config", models.JSONField(default=dict)),
                ("db_next_post_number", models.IntegerField(default=1)),
                (
                    "db_last_activity",
                    models.DateTimeField(default=athanor.utils.utcnow),
                ),
                (
                    "db_attributes",
                    models.ManyToManyField(
                        help_text="attributes on this object. An attribute can hold any pickle-able python object (see docs for special cases).",
                        to="typeclasses.attribute",
                    ),
                ),
                (
                    "db_collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boards",
                        to="athanor_boards.boardcollectiondb",
                    ),
                ),
                (
                    "db_tags",
                    models.ManyToManyField(
                        help_text="tags on this object. Tags are simple string markers to identify, group and alias objects.",
                        to="typeclasses.tag",
                    ),
                ),
                ("db_deleted", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-db_collection", "db_order"],
                "unique_together": {
                    ("db_collection", "db_key"),
                    ("db_collection", "db_order"),
                },
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disguise", models.CharField(blank=True, max_length=255, null=True)),
                ("number", models.IntegerField()),
                ("reply_number", models.IntegerField(default=0)),
                ("subject", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(default=athanor.utils.utcnow)),
                ("date_modified", models.DateTimeField(default=athanor.utils.utcnow)),
                ("body", models.TextField()),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="athanor_boards.boarddb",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="objects.objectdb",
                    ),
                ),
                (
                    "read",
                    models.ManyToManyField(
                        related_name="read_posts", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["board", "number", "reply_number"],
                "unique_together": {("board", "number", "reply_number")},
            },
        ),
    ]
